// pages/translate.tsx

import Head from "next/head";
import Link from "next/link";
import { api } from "~/utils/api";
import { useState } from "react";
import { useRouter } from "next/router";

export default function Translate() {
    const hello = api.example.hello.useQuery({ text: "from tRPC" });
  
    return (
      <>
        <Head>
          <title>VU AI</title>
          <meta name="description" content="Generated by create-t3-app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <main className="flex min-h-screen flex-col items-center justify-center bg-gradient-to-b from-[#2e026d] to-[#15162c]">
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
            <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
              Course<span className="text-[hsl(280,100%,70%)]"> List</span>!
            </h1>             
          </div>
          <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">  
          {/* create a table of courses */}
          <table className="table-auto text-white">
            <thead>
              <tr>
                <th className="px-4 py-2">Course Name</th>
                <th className="px-4 py-2">Course Description</th>
                <th className="px-4 py-2">Course Link</th>
              </tr>
            </thead>
            <tbody>
              <tr>
                <td className="border px-4 py-2">Course 1</td>
                <td className="border px-4 py-2 ">Course 1 Description</td>
                <td className="border px-4 py-2">Course 1 Link</td>
              </tr>
              <tr className="bg-white-100">
                <td className="border px-4 py-2">Course 2</td>
                <td className="border px-4 py-2">Course 2 Description</td>
                <td className="border px-4 py-2">Course 2 Link</td>
              </tr>
              <tr>
                <td className="border px-4 py-2">Course 3</td>
                <td className="border px-4 py-2">Course 3 Description</td>
                <td className="border px-4 py-2">Course 3 Link</td>
              </tr>
            </tbody>
          </table>
           </div>
        </main>
      </>
    );
  }

