import Head from "next/head";
import Link from "next/link";

import { api } from "~/utils/api";
  export default function Home() {
  const hello = api.example.hello.useQuery({ text: "from tRPC" });

  return (
    <>
      <Head>
        <title>YourStudyBuddy</title>
        <meta name="description" content="YourStudyBuddy" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-start bg-[#ffff]">
      <nav className="flex items-center justify-end w-screen h-10 bg-black">
            <div className="lg:gap-16 gap-4 md:px-8">
              {/* Create a link to bring to the education section which is on the same page*/}
              <Link href="/#education" className="lg:text-lg  text-xs font-bold text-white hover:text-[#283044]">
                Profile
              </Link>
            </div>
          </nav>
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">


          <h1 className="text-5xl font-extrabold tracking-tight text-black sm:text-[5rem]">
            Learn with <span className="text-[#808080]">Andl</span>!
          </h1>
          <h2 className="text-2xl font-bold text-black">
            Your Study Buddy! 😁
          </h2>
          <div className="grid grid-cols-1 gap-4 sm:grid-cols-2 md:gap-8">
            {/*Make a div which should be wider and taller than the other two divs */}
            
            <div className="flex max-w-xs height-125vh flex-col gap-4 rounded-xl bg-[#808080]/20 p-4 text-black hover:bg-[#808080]/40">
              <h3 className="text-2xl font-bold">Your History</h3>
              <div className="text-lg">
                View your past contributions or interactions with Andl!
              </div>
            </div>
            <div className="flex max-w-xs flex-col gap-4 rounded-xl bg-[#808080]/20 p-4 text-black hover:bg-[#808080]/40">
              <h3 className="text-2xl font-bold">Courses</h3>
              <div className="text-lg">
                View your courses (or enroll into new ones 😉).
              </div>
            </div>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-[#808080]/20 p-4 text-black hover:bg-[#808080]/40"
              href="/courses"
              target="_blank"
            >
              <h3 className="text-2xl font-bold">Quiz Generations</h3>
              <div className="text-lg">
                Generate quizzes for your courses or take quizzes generated by Andl (AI)!
              </div>
            </Link>
            <Link
              className="flex max-w-xs flex-col gap-4 rounded-xl bg-[#808080]/20 p-4 text-black hover:bg-[#808080]/40"
              target="_blank"
              href="/actions"
            >
              <h3 className="text-2xl font-bold">Forums</h3>
              <div className="text-lg">
                Ask questions or answer questions from other students!
              </div>
            </Link>
          </div>

        </div>
      </main>
    </>
  );
}
